services:
  employee-api:
    container_name: employee-api
    image: challenge/employee-api:0.0.1-SNAPSHOT
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
    networks:
      - challenge
    ports:
      - "8080:8080"

networks:
  challenge: {}