insert into employee values (default, 'Lucas Oliveira', 'Marketing', 7400);
insert into employee values (default, 'Gabriela Santos', 'IT', 8100);
insert into employee values (default, 'Fernanda Almeida', 'Sales', 6500);
insert into employee values (default, 'Thiago Silva', 'Finance', 9800);
insert into employee values (default, 'Isabela Costa', 'Human Resources', 5700);
insert into employee values (default, 'Matheus Ferreira', 'Marketing', 6900);
insert into employee values (default, 'Juliana Rodrigues', 'IT', 7600);
insert into employee values (default, 'Rafaela Oliveira', 'Sales', 7200);
insert into employee values (default, 'Gustavo Alves', 'Finance', 8500);
insert into employee values (default, 'Mariana Santos', 'Human Resources', 5300);
insert into employee values (default, 'Bruno Silva', 'Marketing', 6100);
insert into employee values (default, 'Carolina Costa', 'IT', 8200);
insert into employee values (default, 'João Pereira', 'Sales', 7800);
insert into employee values (default, 'Larissa Almeida', 'Finance', 9300);
insert into employee values (default, 'Rodrigo Fernandes', 'Human Resources', 5900);
insert into employee values (default, 'Amanda Souza', 'Marketing', 7000);
insert into employee values (default, 'Pedro Carvalho', 'IT', 8800);
insert into employee values (default, 'Renata Santos', 'Sales', 7500);
insert into employee values (default, 'Daniel Oliveira', 'Finance', 9600);
insert into employee values (default, 'Ana Rodrigues', 'Human Resources', 5400);